# print('hello' 'world')
# print('hello' , 'world')
# print('hello'+'   '+'world')
# print('Python',3)
# print('Python'+' '+str(3))

# print(1,2,3,4,5)
# print(str(1)+'  '+str(2)+'  '+str(3)+'  '+str(4)+'  '+str(5))

# print(1,2,3,4,5,sep='')
# print(1,2,3,4,5,sep=' ')
# print(1,2,3,4,5,sep='  ')
# print(1,2,3,4,5,sep='-')
# print(1,2,3,4,5,sep='- ')
# print(1,2,3,4,5,sep='@')
# print(1,2,3,4,5,sep=' @ ')
# print('h' 'd')
# print('h' 'd',sep=' ')
# print('h', 'd',sep=' ')
# print('h', 'd',sep='')
# print('Python' , '3.10.4',sep='-')